@startuml ActivityDiagram
skinparam linetype ortho

start 
:Check water temperature;
:Check water quality;
end
@enduml

@startuml ActivityDiagramTemp
start

fork 
    :Read Water Temperature;
fork again 
    :Read Room Temperature;
end fork 

if (water warmer than room?) is (yes) then 
   if (water above target temperature?) is (yes) then 
        :Turn on cooler;
        :Turn off heater;
    else (no)
        if (water more than 3 degrees below target temperature?) is (yes) then 
            :Turn on heater;
            :Turn off cooler;
        else (no)
            :Turn off heater;
            :Turn off cooler;
        endif
   endif
else (no)
    if (water below target temperature?) is (yes) then 
        :Turn on heater;
        :Turn off cooler;
    else (no)
        if (water more than 3 degrees above target temperature?) is (yes) then 
            :Turn on cooler;
            :Turn off heater;
        else (no)
            :Turn off heater;
            :Turn off cooler;
        endif
   endif
endif
end
@enduml


@startuml ActivityDiagramQuality
start
:Clear bad water quality notifications;
:Read pH value;
if (pH value out of safe ranges?) is (yes) then 
    :Turn on either pH dosing pump;
else  (no)
    :Turn off the pH dosing pumps;
endif

end

@enduml