@startuml ClassDiagram
skinparam linetype ortho

interface IThermometer{
    + readTemperature() : float
}

interface ICooler{
    + turnOn() : void
    + turnOff() : void
}

interface IHeater{
    + turnOn() : void
    + turnOff() : void
}

interface IpHSensor{
    + readPH() : float
}

interface IPHDosingPump{
    + turnOn() : void
    + turnOff() : void
}

class TurtleGuard{
    - temperatureManager : TemperatureManager
    - waterQualityManager : WaterQualityManager
    + main() : void
}

class TemperatureManager{
    - waterThermometer : IThermometer
    - roomThermometer : IThermometer
    - heater : IHeater
    - cooler : ICooler
    - targetTemperature : float
    + setWaterTemperature(celsius : float) : void
    + checkTemperatureRange() : void
    + enableHeater() : void
    + enableCooler() : void
}

class WaterQualityManager{
    - phSensor : IpHSensor
    - increasingPHPump : IPHDosingPump
    - decreasingPHPump : IPHDosingPump
    - minPH : float 
    - maxPH : float 
    + setPHLimits(minPH : float, maxPH: float) : void
    + checkWaterQuality() : void
    + enableIncreasingPump() : void
    + enableDecreasingPump() : void
}

class DS18B20{
    - dataPin : int
    + read() : float
}

class MCP9808{
    - I2CAddress : int
    + read() : float
}

class PHCircuit{
    - txPort : int 
    - rxPort: int
    + read() : float
}

class Relay{
    - pinNumber : int
    + turnOn() : void
    + turnOff() : void
}

IThermometer --|> DS18B20
IThermometer --|> MCP9808
IpHSensor --|> PHCircuit
IHeater --|> Relay
ICooler --|> Relay
IPHDosingPump --|> Relay

WaterQualityManager *-- "1" IpHSensor
WaterQualityManager *-- "1" IPHDosingPump
TemperatureManager  *-- "2" IThermometer
TemperatureManager *-- "1" IHeater
TemperatureManager *-- "1" ICooler

TurtleGuard *-- "1" WaterQualityManager
TurtleGuard *-- "1" TemperatureManager

@enduml
